### ISSUE TITLE
sibilant not working in chrome!!

### ISSUE THREAD

**Issue by sarahkemi** [dcalacci/sibilant#3]
I have a fix for it though, will make pull request?

**Comment by atsepkov** [comment]
Out of curiosity, what is the fix?

**Comment by dcalacci** [comment]
I think this can be closed, it works in chrome -- @atsepkov, are you running into issues?

**Comment by sarahkemi** [comment]
I'll close it now! @atsepkov you can check out the fix here #4 :)
